# Generated by Django 5.0.3 on 2024-04-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num", models.IntegerField(help_text="고유번호")),
                ("title", models.CharField(max_length=50)),
                ("content", models.CharField(max_length=200)),
            ],
        ),
    ]
